name: Test

on:
  push:
    branches:
      - main

jobs:
  greeting:
    name: Intro
    runs-on: ubuntu-latest
    steps:
      - name: intro
        run: echo "This is the Test script..."

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 5.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test api
        env:
          CI: true
